//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from pddl.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace PDDLNET {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IpddlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class pddlBaseListener : IpddlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.pddlDoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPddlDoc([NotNull] pddlParser.PddlDocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.pddlDoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPddlDoc([NotNull] pddlParser.PddlDocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.domain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomain([NotNull] pddlParser.DomainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.domain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomain([NotNull] pddlParser.DomainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.domainName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomainName([NotNull] pddlParser.DomainNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.domainName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomainName([NotNull] pddlParser.DomainNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.requireDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequireDef([NotNull] pddlParser.RequireDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.requireDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequireDef([NotNull] pddlParser.RequireDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.typesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypesDef([NotNull] pddlParser.TypesDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.typesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypesDef([NotNull] pddlParser.TypesDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.typedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedNameList([NotNull] pddlParser.TypedNameListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.typedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedNameList([NotNull] pddlParser.TypedNameListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.singleTypeNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleTypeNameList([NotNull] pddlParser.SingleTypeNameListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.singleTypeNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleTypeNameList([NotNull] pddlParser.SingleTypeNameListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.r_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR_type([NotNull] pddlParser.R_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.r_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR_type([NotNull] pddlParser.R_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.primType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimType([NotNull] pddlParser.PrimTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.primType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimType([NotNull] pddlParser.PrimTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionsDef([NotNull] pddlParser.FunctionsDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionsDef([NotNull] pddlParser.FunctionsDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionList([NotNull] pddlParser.FunctionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionList([NotNull] pddlParser.FunctionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicFunctionSkeleton"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicFunctionSkeleton([NotNull] pddlParser.AtomicFunctionSkeletonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicFunctionSkeleton"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicFunctionSkeleton([NotNull] pddlParser.AtomicFunctionSkeletonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSymbol([NotNull] pddlParser.FunctionSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSymbol([NotNull] pddlParser.FunctionSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionType([NotNull] pddlParser.FunctionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionType([NotNull] pddlParser.FunctionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.constantsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantsDef([NotNull] pddlParser.ConstantsDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.constantsDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantsDef([NotNull] pddlParser.ConstantsDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.predicatesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicatesDef([NotNull] pddlParser.PredicatesDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.predicatesDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicatesDef([NotNull] pddlParser.PredicatesDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicFormulaSkeleton"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicFormulaSkeleton([NotNull] pddlParser.AtomicFormulaSkeletonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicFormulaSkeleton"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicFormulaSkeleton([NotNull] pddlParser.AtomicFormulaSkeletonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] pddlParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] pddlParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.typedVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedVariableList([NotNull] pddlParser.TypedVariableListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.typedVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedVariableList([NotNull] pddlParser.TypedVariableListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.singleTypeVarList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleTypeVarList([NotNull] pddlParser.SingleTypeVarListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.singleTypeVarList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleTypeVarList([NotNull] pddlParser.SingleTypeVarListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.constraints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstraints([NotNull] pddlParser.ConstraintsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.constraints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstraints([NotNull] pddlParser.ConstraintsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.structureDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructureDef([NotNull] pddlParser.StructureDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.structureDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructureDef([NotNull] pddlParser.StructureDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.actionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionDef([NotNull] pddlParser.ActionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.actionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionDef([NotNull] pddlParser.ActionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.actionSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionSymbol([NotNull] pddlParser.ActionSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.actionSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionSymbol([NotNull] pddlParser.ActionSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.actionDefBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionDefBody([NotNull] pddlParser.ActionDefBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.actionDefBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionDefBody([NotNull] pddlParser.ActionDefBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.precondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrecondition([NotNull] pddlParser.PreconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.precondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrecondition([NotNull] pddlParser.PreconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.goalDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGoalDesc([NotNull] pddlParser.GoalDescContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.goalDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGoalDesc([NotNull] pddlParser.GoalDescContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFComp([NotNull] pddlParser.FCompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFComp([NotNull] pddlParser.FCompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicTermFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicTermFormula([NotNull] pddlParser.AtomicTermFormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicTermFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicTermFormula([NotNull] pddlParser.AtomicTermFormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] pddlParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] pddlParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durativeActionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDurativeActionDef([NotNull] pddlParser.DurativeActionDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durativeActionDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDurativeActionDef([NotNull] pddlParser.DurativeActionDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.daDefBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDaDefBody([NotNull] pddlParser.DaDefBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.daDefBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDaDefBody([NotNull] pddlParser.DaDefBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.daGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDaGD([NotNull] pddlParser.DaGDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.daGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDaGD([NotNull] pddlParser.DaGDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.prefTimedGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefTimedGD([NotNull] pddlParser.PrefTimedGDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.prefTimedGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefTimedGD([NotNull] pddlParser.PrefTimedGDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.timedGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimedGD([NotNull] pddlParser.TimedGDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.timedGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimedGD([NotNull] pddlParser.TimedGDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.timeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimeSpecifier([NotNull] pddlParser.TimeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.timeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimeSpecifier([NotNull] pddlParser.TimeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.interval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterval([NotNull] pddlParser.IntervalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.interval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterval([NotNull] pddlParser.IntervalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.derivedDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDerivedDef([NotNull] pddlParser.DerivedDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.derivedDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDerivedDef([NotNull] pddlParser.DerivedDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFExp([NotNull] pddlParser.FExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFExp([NotNull] pddlParser.FExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fExp2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFExp2([NotNull] pddlParser.FExp2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fExp2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFExp2([NotNull] pddlParser.FExp2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFHead([NotNull] pddlParser.FHeadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFHead([NotNull] pddlParser.FHeadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.effect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEffect([NotNull] pddlParser.EffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.effect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEffect([NotNull] pddlParser.EffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.cEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCEffect([NotNull] pddlParser.CEffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.cEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCEffect([NotNull] pddlParser.CEffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.pEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPEffect([NotNull] pddlParser.PEffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.pEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPEffect([NotNull] pddlParser.PEffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.condEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondEffect([NotNull] pddlParser.CondEffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.condEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondEffect([NotNull] pddlParser.CondEffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.binaryOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryOp([NotNull] pddlParser.BinaryOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.binaryOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryOp([NotNull] pddlParser.BinaryOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.binaryComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryComp([NotNull] pddlParser.BinaryCompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.binaryComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryComp([NotNull] pddlParser.BinaryCompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignOp([NotNull] pddlParser.AssignOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignOp([NotNull] pddlParser.AssignOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durationConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDurationConstraint([NotNull] pddlParser.DurationConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durationConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDurationConstraint([NotNull] pddlParser.DurationConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.simpleDurationConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleDurationConstraint([NotNull] pddlParser.SimpleDurationConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.simpleDurationConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleDurationConstraint([NotNull] pddlParser.SimpleDurationConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDurOp([NotNull] pddlParser.DurOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDurOp([NotNull] pddlParser.DurOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDurValue([NotNull] pddlParser.DurValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDurValue([NotNull] pddlParser.DurValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.daEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDaEffect([NotNull] pddlParser.DaEffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.daEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDaEffect([NotNull] pddlParser.DaEffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.timedEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimedEffect([NotNull] pddlParser.TimedEffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.timedEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimedEffect([NotNull] pddlParser.TimedEffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fAssignDA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFAssignDA([NotNull] pddlParser.FAssignDAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fAssignDA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFAssignDA([NotNull] pddlParser.FAssignDAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fExpDA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFExpDA([NotNull] pddlParser.FExpDAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fExpDA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFExpDA([NotNull] pddlParser.FExpDAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.assignOpT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignOpT([NotNull] pddlParser.AssignOpTContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.assignOpT"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignOpT([NotNull] pddlParser.AssignOpTContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.problem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProblem([NotNull] pddlParser.ProblemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.problem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProblem([NotNull] pddlParser.ProblemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.problemDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProblemDecl([NotNull] pddlParser.ProblemDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.problemDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProblemDecl([NotNull] pddlParser.ProblemDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.problemDomain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProblemDomain([NotNull] pddlParser.ProblemDomainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.problemDomain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProblemDomain([NotNull] pddlParser.ProblemDomainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.objectDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectDecl([NotNull] pddlParser.ObjectDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.objectDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectDecl([NotNull] pddlParser.ObjectDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit([NotNull] pddlParser.InitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit([NotNull] pddlParser.InitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.initEl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitEl([NotNull] pddlParser.InitElContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.initEl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitEl([NotNull] pddlParser.InitElContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.nameLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameLiteral([NotNull] pddlParser.NameLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.nameLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameLiteral([NotNull] pddlParser.NameLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicNameFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicNameFormula([NotNull] pddlParser.AtomicNameFormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicNameFormula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicNameFormula([NotNull] pddlParser.AtomicNameFormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.goal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGoal([NotNull] pddlParser.GoalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.goal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGoal([NotNull] pddlParser.GoalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.probConstraints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProbConstraints([NotNull] pddlParser.ProbConstraintsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.probConstraints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProbConstraints([NotNull] pddlParser.ProbConstraintsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.prefConGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefConGD([NotNull] pddlParser.PrefConGDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.prefConGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefConGD([NotNull] pddlParser.PrefConGDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.metricSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetricSpec([NotNull] pddlParser.MetricSpecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.metricSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetricSpec([NotNull] pddlParser.MetricSpecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.optimization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptimization([NotNull] pddlParser.OptimizationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.optimization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptimization([NotNull] pddlParser.OptimizationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.metricFExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetricFExp([NotNull] pddlParser.MetricFExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.metricFExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetricFExp([NotNull] pddlParser.MetricFExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.conGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConGD([NotNull] pddlParser.ConGDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.conGD"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConGD([NotNull] pddlParser.ConGDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] pddlParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] pddlParser.NameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace PDDLNET
