//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from pddl.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace PDDLNET {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="pddlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IpddlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.pddlDoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPddlDoc([NotNull] pddlParser.PddlDocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.pddlDoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPddlDoc([NotNull] pddlParser.PddlDocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomain([NotNull] pddlParser.DomainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomain([NotNull] pddlParser.DomainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.domainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomainName([NotNull] pddlParser.DomainNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.domainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomainName([NotNull] pddlParser.DomainNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.requireDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequireDef([NotNull] pddlParser.RequireDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.requireDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequireDef([NotNull] pddlParser.RequireDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.typesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypesDef([NotNull] pddlParser.TypesDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.typesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypesDef([NotNull] pddlParser.TypesDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.typedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedNameList([NotNull] pddlParser.TypedNameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.typedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedNameList([NotNull] pddlParser.TypedNameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.singleTypeNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleTypeNameList([NotNull] pddlParser.SingleTypeNameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.singleTypeNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleTypeNameList([NotNull] pddlParser.SingleTypeNameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.r_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR_type([NotNull] pddlParser.R_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.r_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR_type([NotNull] pddlParser.R_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.primType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimType([NotNull] pddlParser.PrimTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.primType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimType([NotNull] pddlParser.PrimTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionsDef([NotNull] pddlParser.FunctionsDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionsDef([NotNull] pddlParser.FunctionsDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionList([NotNull] pddlParser.FunctionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionList([NotNull] pddlParser.FunctionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicFunctionSkeleton"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicFunctionSkeleton([NotNull] pddlParser.AtomicFunctionSkeletonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicFunctionSkeleton"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicFunctionSkeleton([NotNull] pddlParser.AtomicFunctionSkeletonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSymbol([NotNull] pddlParser.FunctionSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSymbol([NotNull] pddlParser.FunctionSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionType([NotNull] pddlParser.FunctionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionType([NotNull] pddlParser.FunctionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.constantsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantsDef([NotNull] pddlParser.ConstantsDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.constantsDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantsDef([NotNull] pddlParser.ConstantsDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.predicatesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicatesDef([NotNull] pddlParser.PredicatesDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.predicatesDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicatesDef([NotNull] pddlParser.PredicatesDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicFormulaSkeleton"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicFormulaSkeleton([NotNull] pddlParser.AtomicFormulaSkeletonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicFormulaSkeleton"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicFormulaSkeleton([NotNull] pddlParser.AtomicFormulaSkeletonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] pddlParser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] pddlParser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.typedVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedVariableList([NotNull] pddlParser.TypedVariableListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.typedVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedVariableList([NotNull] pddlParser.TypedVariableListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.singleTypeVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleTypeVarList([NotNull] pddlParser.SingleTypeVarListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.singleTypeVarList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleTypeVarList([NotNull] pddlParser.SingleTypeVarListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.constraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraints([NotNull] pddlParser.ConstraintsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.constraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraints([NotNull] pddlParser.ConstraintsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.structureDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructureDef([NotNull] pddlParser.StructureDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.structureDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructureDef([NotNull] pddlParser.StructureDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.actionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionDef([NotNull] pddlParser.ActionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.actionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionDef([NotNull] pddlParser.ActionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.actionSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionSymbol([NotNull] pddlParser.ActionSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.actionSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionSymbol([NotNull] pddlParser.ActionSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.actionDefBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionDefBody([NotNull] pddlParser.ActionDefBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.actionDefBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionDefBody([NotNull] pddlParser.ActionDefBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.precondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecondition([NotNull] pddlParser.PreconditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.precondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecondition([NotNull] pddlParser.PreconditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.goalDesc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoalDesc([NotNull] pddlParser.GoalDescContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.goalDesc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoalDesc([NotNull] pddlParser.GoalDescContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFComp([NotNull] pddlParser.FCompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFComp([NotNull] pddlParser.FCompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicTermFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicTermFormula([NotNull] pddlParser.AtomicTermFormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicTermFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicTermFormula([NotNull] pddlParser.AtomicTermFormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] pddlParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] pddlParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durativeActionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDurativeActionDef([NotNull] pddlParser.DurativeActionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durativeActionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDurativeActionDef([NotNull] pddlParser.DurativeActionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.daDefBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDaDefBody([NotNull] pddlParser.DaDefBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.daDefBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDaDefBody([NotNull] pddlParser.DaDefBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.daGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDaGD([NotNull] pddlParser.DaGDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.daGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDaGD([NotNull] pddlParser.DaGDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.prefTimedGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefTimedGD([NotNull] pddlParser.PrefTimedGDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.prefTimedGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefTimedGD([NotNull] pddlParser.PrefTimedGDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.timedGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimedGD([NotNull] pddlParser.TimedGDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.timedGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimedGD([NotNull] pddlParser.TimedGDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.timeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimeSpecifier([NotNull] pddlParser.TimeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.timeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimeSpecifier([NotNull] pddlParser.TimeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterval([NotNull] pddlParser.IntervalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterval([NotNull] pddlParser.IntervalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.derivedDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDerivedDef([NotNull] pddlParser.DerivedDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.derivedDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDerivedDef([NotNull] pddlParser.DerivedDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFExp([NotNull] pddlParser.FExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFExp([NotNull] pddlParser.FExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fExp2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFExp2([NotNull] pddlParser.FExp2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fExp2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFExp2([NotNull] pddlParser.FExp2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFHead([NotNull] pddlParser.FHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFHead([NotNull] pddlParser.FHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.effect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEffect([NotNull] pddlParser.EffectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.effect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEffect([NotNull] pddlParser.EffectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.cEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCEffect([NotNull] pddlParser.CEffectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.cEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCEffect([NotNull] pddlParser.CEffectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.pEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPEffect([NotNull] pddlParser.PEffectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.pEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPEffect([NotNull] pddlParser.PEffectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.condEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondEffect([NotNull] pddlParser.CondEffectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.condEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondEffect([NotNull] pddlParser.CondEffectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOp([NotNull] pddlParser.BinaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOp([NotNull] pddlParser.BinaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.binaryComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryComp([NotNull] pddlParser.BinaryCompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.binaryComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryComp([NotNull] pddlParser.BinaryCompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignOp([NotNull] pddlParser.AssignOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignOp([NotNull] pddlParser.AssignOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durationConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDurationConstraint([NotNull] pddlParser.DurationConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durationConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDurationConstraint([NotNull] pddlParser.DurationConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.simpleDurationConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleDurationConstraint([NotNull] pddlParser.SimpleDurationConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.simpleDurationConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleDurationConstraint([NotNull] pddlParser.SimpleDurationConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDurOp([NotNull] pddlParser.DurOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDurOp([NotNull] pddlParser.DurOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.durValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDurValue([NotNull] pddlParser.DurValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.durValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDurValue([NotNull] pddlParser.DurValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.daEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDaEffect([NotNull] pddlParser.DaEffectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.daEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDaEffect([NotNull] pddlParser.DaEffectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.timedEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimedEffect([NotNull] pddlParser.TimedEffectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.timedEffect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimedEffect([NotNull] pddlParser.TimedEffectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fAssignDA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFAssignDA([NotNull] pddlParser.FAssignDAContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fAssignDA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFAssignDA([NotNull] pddlParser.FAssignDAContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.fExpDA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFExpDA([NotNull] pddlParser.FExpDAContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.fExpDA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFExpDA([NotNull] pddlParser.FExpDAContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.assignOpT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignOpT([NotNull] pddlParser.AssignOpTContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.assignOpT"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignOpT([NotNull] pddlParser.AssignOpTContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.problem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProblem([NotNull] pddlParser.ProblemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.problem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProblem([NotNull] pddlParser.ProblemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.problemDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProblemDecl([NotNull] pddlParser.ProblemDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.problemDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProblemDecl([NotNull] pddlParser.ProblemDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.problemDomain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProblemDomain([NotNull] pddlParser.ProblemDomainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.problemDomain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProblemDomain([NotNull] pddlParser.ProblemDomainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.objectDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectDecl([NotNull] pddlParser.ObjectDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.objectDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectDecl([NotNull] pddlParser.ObjectDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit([NotNull] pddlParser.InitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit([NotNull] pddlParser.InitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.initEl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitEl([NotNull] pddlParser.InitElContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.initEl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitEl([NotNull] pddlParser.InitElContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.nameLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameLiteral([NotNull] pddlParser.NameLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.nameLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameLiteral([NotNull] pddlParser.NameLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.atomicNameFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicNameFormula([NotNull] pddlParser.AtomicNameFormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.atomicNameFormula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicNameFormula([NotNull] pddlParser.AtomicNameFormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.goal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoal([NotNull] pddlParser.GoalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.goal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoal([NotNull] pddlParser.GoalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.probConstraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProbConstraints([NotNull] pddlParser.ProbConstraintsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.probConstraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProbConstraints([NotNull] pddlParser.ProbConstraintsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.prefConGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefConGD([NotNull] pddlParser.PrefConGDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.prefConGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefConGD([NotNull] pddlParser.PrefConGDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.metricSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetricSpec([NotNull] pddlParser.MetricSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.metricSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetricSpec([NotNull] pddlParser.MetricSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.optimization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptimization([NotNull] pddlParser.OptimizationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.optimization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptimization([NotNull] pddlParser.OptimizationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.metricFExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetricFExp([NotNull] pddlParser.MetricFExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.metricFExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetricFExp([NotNull] pddlParser.MetricFExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.conGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConGD([NotNull] pddlParser.ConGDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.conGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConGD([NotNull] pddlParser.ConGDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pddlParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] pddlParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pddlParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] pddlParser.NameContext context);
}
} // namespace PDDLNET
